### ISSUE TITLE
Lane labelling

### ISSUE THREAD

**Issue by thibault-charlottin** [I24-MOTION/I24M_improvement_tracker#4]
Hello,
First of all, thank you for this data sharing.
I am trying to label for each timestamp the current lane for each vehicle but I do not find any indication of the lane separation coordinates.
Yet in your part C paper, you show several space-time diagrams lane by lane.

Could you help me with this lane detection?

Thanks in advance

**Comment by junyi9** [comment]
The column _y_position_ (ft) in the dataset can be used to identify the lane information. 
For the data in direction _-1_:
  - 12 - 24, lane 1 (HOV lane)
  - 24 - 36, lane 2
  - 36 - 48, lane 3
  - 48 - 60, lane 4
The lane positions are roughly approximated as constant lateral ranges, estimated by averaging the lateral coordinates of all lane markings for each lane.

**Comment by barbourww** [comment]
@thibault-charlottin Let us know if this answer by @junyi9 answers your questions. We might go ahead and update the documentation with these lane y-value ranges.

**Comment by thibault-charlottin** [comment]
Hello thanks for your help, it is exactly what I needed. I think that it would be beneficial to the other users of the dataset to have this information

**Comment by barbourww** [comment]
Added this information in latest commit of documentation https://github.com/I24-MOTION/I24M_documentation/commit/9f8a9158ba0bcbfdd525f4be771f8d45ad1bd4df
